### ISSUE TITLE
9/8 1st Study to-do list

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/SSAC_Basic_Python_BTeam#1]
- [x] 스터디 공유 채널 만들기
- [x]  패스트 캠퍼스 온라인 강좌 선정
- [x] 스터디 방향성 정하기
- [x] 스터디 월별 목표 정하기, 주당 온라인 강좌 개수 정하기
- [x] 스터디 규칙 정하기
- [x] 스터디 리더 정하기, 리더 방식 (순환방식, 전임 방식)
- [x] 9/15(수요일) 스터디 참여 방식(온라인, 오프라인) 정하기

**Comment by seungjaepack** [comment]
- 패스트 캠퍼스 온라인 강좌 
- 카테고리 > 데이터 사이언스
1. 직장인을 위한 파이썬 데이터 분석 올인원 패키지 On-line (Basic)
2. 파이썬을 활용한 데이터 전처리 Level Up 올인원 패키지 On-line (Middle)
3. 파이썬을 활용한 시계열 데이터 분석 A-Z 올인원 패키지 (Middle)

**Comment by seungjaepack** [comment]
- 주당 온라인 강좌 개수 정하기 : 최소 2개

**Comment by seungjaepack** [comment]
- 강좌 당 퀴즈 : 1개 ( 옵션 강좌 요약 정리 1개로 대체 가능)
# 퀴즈의 개수는 1~3개 정도로 강좌의 내용 별 팀원 재량 것 수를 조정해서 작성할 것

**Comment by seungjaepack** [comment]
- 9/15 스터디 참여 방식 온라인으로 참여

**Comment by seungjaepack** [comment]
- 온라인 강의 선택  : 직장인을 위한 파이썬 데이터 분석 올인원 패키지 On-line (Basic)

**Comment by seungjaepack** [comment]
- GROUD Rules
   - 1. 팀원과 토론을 포함 대화 시  존중과 배려 할 것
   - 2. 월 별 계획을 월 단위로 체크
   - 3. 불참 시 하루 전 팀원에게 전달하기
   - 4. 패널티 : 
         - 스터디 불참 (짝수) 시 마다 팀원에게 스타벅스 기프티콘 선물하기
