### ISSUE TITLE
10/28 To-do-list

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/SSAC_Basic_Python_BTeam#10]
- [x] 온라인 강의 리뷰 : 직장인을 위한 파이썬_데이터 분석을 위한 준비_Pandas

- [x]  온라인 강의 진도 체크
- 10월 목표 :
- Python Main : 김용담 강사님 파이썬 (10월 완료)
- Python Study : 직장인을 위한 파이썬 데이터 분석 올인원 패키지 On-line 강좌[Pandas 완료]

- [x]  10/28 스터디 데일리 플랜 :  16:00~ 18:00

- [x] 온라인 강의 퀴즈 리뷰

- [x] 온/오프라인 강의 리뷰 (수학적 통계 강의 내용 모르는 부분 질문) 

- [x] 11월 1주차 스터디 일자 확인 : 11/2 화요일 16:00

- [x] 기타 스터디 조정 내용 체크

 기타 스터디 조정 내용 체크
