### ISSUE TITLE
11/02 To-do-list

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/SSAC_Basic_Python_BTeam#11]
- [x] 온라인 강의 리뷰 : 직장인을 위한 파이썬_데이터 분석을 위한 준비_Pandas

- [x]  온라인 강의 진도 체크
- 11월 목표 설정:
- Python Study : 직장인을 위한 파이썬 데이터 분석 올인원 패키지 On-line 강좌 : Seaborn완료, machine learning 초반 진입
- 11월 1주차 : matplotlib 01~06
- 11월 2주차 : matplotlib 07~15

- [x]  11/02 스터디 데일리 플랜 :  16:00~ 18:00

- [x] 온라인 강의 퀴즈 리뷰

- [x] 온/오프라인 강의 리뷰 (머신러닝 수업 강의 내용 모르는 부분 질문) 

- [x] 11월 2주차 스터디 일자 확인 : 금주 상담일정 정해지면 Slack을 통해 계획

- [x] 기타 스터디 조정 내용 체크

 기타 스터디 조정 내용 체크

**Comment by seungjaepack** [comment]
- 빅데이터 분석 유즈 케이스
1) 서울 특별시 빅데이터 캠퍼스 : https://bigdata.seoul.go.kr/noti/selectPageListTabNoti.do?r_id=P260
2) 유튜브 분석 해설 영상 : https://www.youtube.com/c/todaycode/videos

- 빅데이터 경진 대회
1) https://data.g2b.go.kr:1443/pt/main/index.do

**Comment by seungjaepack** [comment]
### Quiz Review
1. Matplot lib을 통한 시각화의 강점: df를 인덱싱하고 바로 시각화 하기 용이함
-df_seoul["분양가"].plot(kind="box")
2. 박스 플럿 해석
- 박스 플럿의 사용 용도 : 아웃라이어확인, 중앙치로 부터의 데이터 분포 확인
- 사분위 범위 : 3Q-1Q
- IQR : (3Q-1Q) * 1.5
- box plot max : 3Q+IQR
- box plot min : 1Q-IQR
- box plot의 max값과 데이터의 max값과 다를 수 있다. (outlier가 존재하는 경우)
3. Hexbin plot 활용 : 고밀도 산점도 그래프, scatter plot과 같이 x,y값을 입력해줘야함, gridsize 옵션 설정 가능
- 육각형 범위에 해당하는 데이터의 분포를 확인 가능
- Scaling 후 normalization 확인 시 사용 가능할 것으로 판단됨
4. 다중 함수에서 plt.figure()를 사용하면 새로운 canvas에 각각의 함수를 출력한다.
5. seaborn에서 지원하지 않는 plot은? barh plot
- barh 모양의 plot을 출력할 때는 bar plot에 x,y를 뒤집어서 입력하면 가능함(y,x)
6. heatmap의 수치를 표현하는 옵션은? annot = True
7. histplot에서 등급 범주 별로 색상을 부여할 때 사용하는 옵션은 ? hue =""
