### ISSUE TITLE
11/12 To-do List

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/SSAC_Basic_Python_BTeam#12]
- [x] 온라인 강의 리뷰 : 직장인을 위한 파이썬_데이터 분석을 위한 준비_Pandas

- [x]  온라인 강의 진도 체크
- 11월 목표 설정:
- Python Study : 직장인을 위한 파이썬 데이터 분석 올인원 패키지 On-line 강좌 : Seaborn완료, machine learning 초반 진입
- 11월 1주차 : matplotlib 01~06
- 11월 2주차 : 예측을 위한 머신러닝 라이브러리  Ch 01. 01 ~ 01.02

- [x]  11/12 스터디 데일리 플랜 :  16:00~ 18:00

- [x] 온라인 강의 퀴즈 리뷰

- [x] 온/오프라인 강의 리뷰 (머신러닝 수업 강의 내용 모르는 부분 질문) 

- [x] 11월 3주차 스터디 일자 확인 :  11/18(목요일) : 17:00 ~ 18:00

- [x] 기타 스터디 조정 내용 체크

 기타 스터디 조정 내용 체크

**Comment by seungjaepack** [comment]
## 퀴즈 리뷰
### 산점도 시각화 고려 사항 : 
-  1) subplot형태이며 각 plot은 (1,3,1), (1,3,2), (1,3,3)에 해당한다.
-  2) 산점도는 데이터의 분포를 시각화할 때 사용하며 시각화 시 데이터 x,y를 따로 설정해야함, plt.scattter(x,y)
-  3) 산점도의 option 중 cmap을 사용하면 조합되어 있는 색들을 c에 값들을 지정한 cmap list에 맞춰 변형해서 색깔을 적용할 수 있다.
- 4)  컬러바는 plt.colorbar()로 설정할 수 있다.

### 비교 바 그래프 고려 사항 :
- 1) 상기 그래프는 막대그래프로 넓이 지정과 넓이 설정을 해줘야 한다.
- 2) 막대그래프는 barh타입으로 ytick은 x로 설정해야 한다.

### 영역 그래프 고려 사항 : 
- 1) 각각의 함수에 대해  plt.fill_between을 사용하여 시각화 한 것이다.
- 2) 세 개의 그래프는 fill_beween option 중 color를 각각 다르게 설정 하였다.
- 3) 세 개의 그래프를 동시에 표현하는 경우 그래프가 겹치는 부분은 색이 진해지기 때문에 투명도 (=alpha)를 다르게 설정한다.
- 4) 영역그래프를 사용할 때 x,y값이 필요하다.
