### ISSUE TITLE
11/19 to-do-list

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/SSAC_Basic_Python_BTeam#13]
- [x] 온라인 강의 리뷰 : 직장인을 위한 파이썬_데이터 분석을 위한 준비_Pandas

- [x]  온라인 강의 진도 체크
- 11월 목표 설정: 머신 러닝 학습
- 11월 3주차 :  예측을 위한 머신 러닝 라이브러리  Ch 02. 01 ~ 02.04
- [x]  11/19 스터디 데일리 플랜 :  16:00~ 18:00

- [x] 온라인 강의 퀴즈 리뷰

- [x] 온/오프라인 강의 리뷰 (머신 러닝 수업 강의 내용 모르는 부분 질문) 

- [x] 11월 4주차 스터디 일자 확인 :  차주 프로젝트와 초기 상담 일정 고려하여 조정

- [x] 기타 스터디 조정 내용 체크

 기타 스터디 조정 내용 체크

**Comment by seungjaepack** [comment]
- 리뷰 
# 머신러닝의 원리
## 1. 가설 함수 (Hyphothesis)
- 가설 함수를 통해서 나온 값 -> H(x) = Y Predict
## 2. 손실 함수(Cost, Loss Function)
- 손실(loss) : 예측값과 얼마나 떨어져 있는 가 (예측값- 실제값)
- H(x)(예측값) – Y(실제값)
- 손실의 총합의 오류 ->  손실의 총합이 0인 경우가 한 개가 아님 -> 손실 함수에 제곱을 취해줌 -> 데이터의 개수가 많아지면 손실이 커지므로 전체 손실의 평균을 구함(제곱오차(MSE))
## 3. 경사하강법 (Loss fucntion)
- 손실 함수의 기울기가 최소인 지점을 찾아 나가는 방법
- 과정: 
   1) 모델을 선정한다.
   2) initial W를 설정한다
   3) 손실 함수를 계산한다.
   4) 손실 함수의 기울기를  업데이트하면서 기울기가 최소인 점을 찾는다.
