### ISSUE TITLE
9/23  Study to-do list

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/SSAC_Basic_Python_BTeam#3]
- [x]  수업 리뷰 : Visualization, Crawling (9월 3주차)
- [x] 온라인 강의 리뷰 : 직장인을 위한 파이썬_데이터 분석을 위한 준비_CH01~CH02)
- [x]  온라인 강의 진도 체크 
        -  Python Main
        -  Python Study : 직장인을 위한 파이썬 데이터 분석 올인원 패키지 On-line 강좌
- [x] 9/23 스터디 데일리 플랜 : AM 10:00~ 12:00
     - 온라인 강의 퀴즈 리뷰
     - 온/오프라인 강의 리뷰 (모르는 것 서로 질문)
- [x] 9월 5주차 스터디 일자 확인  : 9월 28일 (화요일) 18:00 ~ 19:00

- [x] 기타 스터디 조정 내용 체크
  - 온라인 강의 수강 계획 재조정 : 현재는 온라인 강의 2개/주로 진행 중
  - 워크 시트 제출 (구글 업로드) : 파일명 현재 날짜와 작성자

**Comment by seungjaepack** [comment]
- 온라인 강의 진도 : 
  1) 직장인을 위한 python:  10월 1주차까지는 Numpy
  2) Python : 10월 말까지 완료

**Comment by seungjaepack** [comment]
- 워크 시트 제출 : 각 주 스터디 전까지 구글 드라이브에 업로드
- 파일 이름 : 주차_이름

**Comment by seungjaepack** [comment]
1. 퀴즈 리뷰
-Numpy : argsort element의 크기에 대한 원소의 위치값(Index) 내림 또는 오름 차순 정리
-Array index : [[index num]]]
-Pandas : Dataframe Slicing : loc, iloc사용
-String 값 처리 : print("".join("","","") 문자열 합치기, print("","","") 문자열 사이에 콤마는 공백을 의미함
