### ISSUE TITLE
9/28 study_group : To-do-list

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/SSAC_Basic_Python_BTeam#4]
- [ ] 온라인 강의 리뷰 : 직장인을 위한 파이썬_데이터 분석을 위한 준비_

- [ ]  온라인 강의 진도 체크

- Python Main : 김용담 강사님 파이썬 
- Python Study : 직장인을 위한 파이썬 데이터 분석 올인원 패키지 On-line 강좌

- [ ]  9/23 스터디 데일리 플랜 :  18:00~ 19:00

- [ ] 온라인 강의 퀴즈 리뷰

- [ ] 온/오프라인 강의 리뷰 (모르는 것 서로 질문)

- [ ] 10월 2주차 스터디 일자 확인 : 10월 5일 (화요일) 18:00 ~ 19:00

- [ ] 기타 스터디 조정 내용 체크

**Comment by seungjaepack** [comment]
- 정다예님 10월 5일 오후 백신 접종

**Comment by seungjaepack** [comment]
- quiz review 
-1) comprehension parameter(input,output), arguement
-2) using pandas visualization lib : violin plot, heat plot
-3) processing data : non, empty value, including '-' char -> replace, fillna, drop,astype,strip
-4) check the type of html parsing : class
