### ISSUE TITLE
10/21 To-do-list

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/SSAC_Basic_Python_BTeam#9]
- [x] 온라인 강의 리뷰 : 직장인을 위한 파이썬_데이터 분석을 위한 준비_Pandas

- [x]  온라인 강의 진도 체크

- Python Main : 김용담 강사님 파이썬 (10월 완료)
- Python Study : 직장인을 위한 파이썬 데이터 분석 올인원 패키지 On-line 강좌

- [x]  10/21 스터디 데일리 플랜 :  18:00~ 19:00

- [x] 온라인 강의 퀴즈 리뷰

- [x] 온/오프라인 강의 리뷰 (수학적 통계 강의 내용 모르는 부분 질문) 

- [x] 10월 4주차 스터디 일자 확인 : 10/28 목요일 14:00

- [x] 기타 스터디 조정 내용 체크

 기타 스터디 조정 내용 체크

**Comment by seungjaepack** [comment]
####Quiz review:
1) Std= np.sqrt((Df[i]-Df.mean())**2 ….+ Df[n]-Df.mean())**2)/n)
2) pd.pivot_table(df, index=’행 인덱스’, columns=’열 인덱스’, values=’조회하고 싶은 값’, aggfunc = np. 함수)
3) 복합 인덱스df.groupby([]) -> Unstack() -> 인덱스 초기화 (reset_index)
4) df.dropna(axis=1, how=”any(or all)”), df.drop_duplicates(“column 명”,first(or last))
